### ISSUE TITLE
Upgrade Celery usage to comply with updated task definition interface

### ISSUE THREAD

**Issue by blarghmatey** [mitodl/edx-git-auto-export#4]
In Celery 4.x they deprecated the `celery.task.task` decorator in favor of a class attribute. In the most recent master branch of edx-platform they are using the 5.2.x release of Celery which fully removes the module path that this plugin is relying on. The proper usage is now to use a format of `@celery_app_instance.task` as the decorator https://docs.celeryq.dev/en/stable/reference/celery.html#celery.Celery.task

The traceback that we are seeing in the master branch is:
```
Traceback (most recent call last):
  File "manage.py", line 103, in <module>
    startup.run()
  File "/edx/app/edxapp/edx-platform/cms/startup.py", line 20, in run
    django.setup()
  File "/edx/app/edxapp/venvs/edxapp/lib/python3.8/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/edx/app/edxapp/venvs/edxapp/lib/python3.8/site-packages/django/apps/registry.py", line 122, in populate
    app_config.ready()
  File "/edx/app/edxapp/venvs/edxapp/lib/python3.8/site-packages/git_auto_export/apps.py", line 23, in ready
    import git_auto_export.signals
  File "/edx/app/edxapp/venvs/edxapp/lib/python3.8/site-packages/git_auto_export/signals.py", line 6, in <module>
    from .tasks import async_export_to_git
  File "/edx/app/edxapp/venvs/edxapp/lib/python3.8/site-packages/git_auto_export/tasks.py", line 1, in <module>
    from celery.task import task
ModuleNotFoundError: No module named 'celery.task'
```

**Comment by blarghmatey** [comment]
This might be the precipitating event that makes it worth moving this package into the [open-edx-plugins](https://github.com/mitodl/open-edx-plugins/) repository.

**Comment by blarghmatey** [comment]
It looks like what we actually want to use in this situation is the `shared_task` decorator. https://docs.celeryq.dev/en/stable/django/first-steps-with-django.html#using-the-shared-task-decorator

**Comment by arslanashraf7** [comment]
@blarghmatey Can we close this ticket?
